export enum AuthModuleErrorCode {
  INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  ALREADY_EXITS_EMAIL = 'AUTH_ALREADY_EXITS_EMAIL',
  PASSWORDS_MISPATCH = 'AUTH_PASSWORDS_MISMATCH',
  INVITAION_EXPIRED = 'AUTH_INVITAION_EXPIRED',
  INVITAION_INVALIDATED = 'AUTH_INVITAION_INVALIDATED',
}
